<?php

namespace Shopware\Core\Framework\DataAbstractionLayer;

use Shopware\Core\Framework\DataAbstractionLayer\Field\Field;

class AttributeEntityDefinition extends EntityDefinition
{
    public function __construct(private readonly array $meta = [])
    {
        parent::__construct();
    }

    public function getEntityClass(): string
    {
        return $this->meta['entity_class'];
    }

    public function getEntityName(): string
    {
        return $this->meta['entity_name'];
    }

    public function getDefaults(): array
    {
        // todo add defaults support
        return parent::getDefaults(); // TODO: Change the autogenerated stub
    }

    protected function getParentDefinitionClass(): ?string
    {
        // todo add `entity_name` support
        return parent::getParentDefinitionClass();
    }

    protected function defineFields(): FieldCollection
    {
        $fields = [];
        foreach ($this->meta['fields'] as $field) {
            if (!isset($field['class'])) {
                continue;
            }

            /** @var Field $instance */
            $instance = new $field['class'](...$field['args']);

            foreach ($field['flags'] ?? [] as $flag) {
                $instance->addFlags(new $flag['class'](...$flag['args'] ?? []));
            }

            $fields[] = $instance;
        }

        return new FieldCollection($fields);
    }
}
